# Generated by Django 5.1.2 on 2024-10-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.IntegerField(choices=[(0, 'not active'), (1, 'active')], default=0),
        ),
    ]
