# Generated by Django 5.1.2 on 2024-11-01 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_is_act_alter_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_act',
        ),
    ]
