# Generated by Django 5.1.2 on 2024-10-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoblieInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Nationality', models.CharField(max_length=20)),
                ('Type', models.CharField(max_length=30, unique=True)),
                ('price', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=20)),
                ('screenSize', models.PositiveIntegerField()),
                ('checkExist', models.IntegerField(choices=[(0, '-'), (1, '+')], default=0)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
    ]
