# Generated by Django 5.1.2 on 2024-11-01 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=20)),
                ('mobile_type', models.CharField(max_length=30, unique=True)),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('color', models.CharField(max_length=20)),
                ('screen_size', models.FloatField()),
                ('check_exist', models.IntegerField(choices=[(0, '-'), (1, '+')], default=0)),
                ('country', models.CharField(max_length=20)),
                ('count', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='MoblieInfo',
        ),
    ]
